require "rake"
require "rake/testtask"
require "rake/rdoctask"
require "benchmark"
require File.join(File.dirname(__FILE__), "scraper")


desc "Generate documentation"
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title    = "Scraper"
  rdoc.options << "--line-numbers"
  rdoc.options << "--inline-source"
  rdoc.rdoc_files.include("README")
  rdoc.rdoc_files.include("lib/**/*.rb")
end


desc "Run all tests"
Rake::TestTask.new(:test) do |test|
    test.libs << "lib"
    test.pattern = "test/**/*_test.rb"
    test.verbose = true
end


