require 'rake'
require 'rake/rdoctask'

desc 'Generate RDoc'
rd = Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = '../doc/output/rdoc-rails'
  rdoc.options << '--title' << 'if_modified' << '--line-numbers' << '--inline-source' << '--main' << 'if_modified'
  rdoc.rdoc_files.include('README', 'MIT-LICENSE', 'lib/**/*.rb')
end
