require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

desc 'Default: run unit tests.'
task :default => :test

desc 'Run all test cases'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate RDoc'
rd = Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = '../doc/output/rdoc-rails'
  rdoc.options << '--title' << 'RestfullyYours' << '--line-numbers' << '--inline-source' << '--main' << 'RestfullyYours'
  rdoc.rdoc_files.include('MIT-LICENSE', 'lib/**/*.rb')
end
